### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by volodymyrzdrok** [volodymyrzdrok/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by vozdrok** [comment]
In September 2018, during an interview, Elon Musk agreed to the offer of comedian Joe Rogan to smoke marijuana (more precisely, a mixture of marijuana and tobacco). Before smoking, Elon asked Rogan if it was legal. Then he said that he rarely smokes pot, since it not only does not have the desired effect on him, but also negatively affects productivity.
